### ISSUE TITLE
Projectiles

### ISSUE THREAD

**Issue by mmcin** [tymaestro/Rockstar-Run#10]

**Comment by tymaestro** [comment]
## Tasks

- [ ] create projectile design
- [ ] speed of projectile
- [ ] create projectile collision area
