### ISSUE TITLE
User has some music and sound fx feedback

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/Rockstar-Run#12]
## Acceptance Criteria
- Audio bg
- Audio for operations

## Tasks
- [x] Headbump sound
- [x] Jump sound
- [x] Teleport sound
- [x] Item
- [x] Special item

**Comment by tymaestro** [comment]
## Tasks

- [x] Create audio for sprites
- [ ] create audio for projectiles
- [x] create endgame audio
- [x] create background audio
- [x] create win sound effect
