### ISSUE TITLE
User has game pieces to interact with

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/Rockstar-Run#2]
## Acceptance Criteria
- There are characters
- there are inanimate objects

## Tasks
- [x] Create sprites
- [x] Load them into assets
- [x] Set up the rendering settings 
- [x] Add to levels
