### ISSUE TITLE
User has a floor to run on

### ISSUE THREAD

**Issue by tymaestro** [tymaestro/Rockstar-Run#8]

**Comment by mmcin** [comment]
## Acceptance Criteria
- There is a floor 
- User doesn't fall through it

## Tasks
- [x] Add floor sprite to assets
- [x] Add to levels
- [x] Set as solid
